/** Date range options for directory event filters. Applied client-side. */
export const MONTH_OPTIONS = [
  { value: '', label: 'All Dates' },
  { value: 'current', label: 'This Month' },
  { value: 'next', label: 'Next Month' },
  { value: 'next3', label: 'Next 3 Months' },
  { value: 'next6', label: 'Next 6 Months' },
  { value: 'next12', label: 'Next 12 Months' },
  { value: 'next18', label: 'Next 18 Months' },
]

/** US states for directory state filter. Applied client-side. */
export const US_STATES = [
  { value: '', label: 'All States' },
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'DC', label: 'Washington DC' },
]

/** Sport options for directory (when Org Type = Sports Club). value/label for dropdown. */
export const SPORTS_OPTIONS = [
  { value: '', label: 'All Sports' },
  { value: 'Running', label: 'Running' },
  { value: 'Golf', label: 'Golf' },
  { value: 'Basketball', label: 'Basketball' },
  { value: 'Baseball', label: 'Baseball' },
  { value: 'Soccer', label: 'Soccer' },
  { value: 'Football', label: 'Football' },
  { value: 'Tennis', label: 'Tennis' },
  { value: 'Volleyball', label: 'Volleyball' },
  { value: 'Swimming', label: 'Swimming' },
  { value: 'Cycling', label: 'Cycling' },
  { value: 'Boxing', label: 'Boxing' },
  { value: 'Wrestling', label: 'Wrestling' },
  { value: 'Martial Arts', label: 'Martial Arts' },
  { value: 'Hockey', label: 'Hockey' },
  { value: 'Rugby', label: 'Rugby' },
  { value: 'Cricket', label: 'Cricket' },
  { value: 'Lacrosse', label: 'Lacrosse' },
  { value: 'Softball', label: 'Softball' },
  { value: 'Track & Field', label: 'Track & Field' },
  { value: 'Cross Country', label: 'Cross Country' },
  { value: 'Triathlon', label: 'Triathlon' },
  { value: 'CrossFit', label: 'CrossFit' },
  { value: 'Rowing', label: 'Rowing' },
  { value: 'Sailing', label: 'Sailing' },
  { value: 'Surfing', label: 'Surfing' },
  { value: 'Skateboarding', label: 'Skateboarding' },
  { value: 'Snowboarding', label: 'Snowboarding' },
  { value: 'Skiing', label: 'Skiing' },
  { value: 'Rock Climbing', label: 'Rock Climbing' },
  { value: 'Hiking', label: 'Hiking' },
  { value: 'Fishing', label: 'Fishing' },
  { value: 'Bowling', label: 'Bowling' },
  { value: 'Pickleball', label: 'Pickleball' },
  { value: 'Badminton', label: 'Badminton' },
  { value: 'Table Tennis', label: 'Table Tennis' },
  { value: 'Racquetball', label: 'Racquetball' },
  { value: 'Squash', label: 'Squash' },
  { value: 'Gymnastics', label: 'Gymnastics' },
  { value: 'Cheerleading', label: 'Cheerleading' },
  { value: 'Dance', label: 'Dance' },
  { value: 'Yoga', label: 'Yoga' },
  { value: 'Pilates', label: 'Pilates' },
  { value: 'Weightlifting', label: 'Weightlifting' },
  { value: 'MMA', label: 'MMA' },
  { value: 'Jiu-Jitsu', label: 'Jiu-Jitsu' },
  { value: 'Karate', label: 'Karate' },
  { value: 'Taekwondo', label: 'Taekwondo' },
  { value: 'Water Polo', label: 'Water Polo' },
  { value: 'Disc Golf', label: 'Disc Golf' },
  { value: 'Ultimate Frisbee', label: 'Ultimate Frisbee' },
  { value: 'Field Hockey', label: 'Field Hockey' },
  { value: 'Ice Skating', label: 'Ice Skating' },
  { value: 'Equestrian', label: 'Equestrian' },
  { value: 'BMX', label: 'BMX' },
  { value: 'Mountain Biking', label: 'Mountain Biking' },
  { value: 'E-Sports', label: 'E-Sports' },
  { value: 'Archery', label: 'Archery' },
  { value: 'Diving', label: 'Diving' },
  { value: 'Fencing', label: 'Fencing' },
  { value: 'Figure Skating', label: 'Figure Skating' },
  { value: 'Judo', label: 'Judo' },
  { value: 'Kayaking', label: 'Kayaking' },
  { value: 'Marathon', label: 'Marathon' },
  { value: 'Mixed Martial Arts', label: 'Mixed Martial Arts' },
  { value: 'Motocross', label: 'Motocross' },
  { value: 'Paintball', label: 'Paintball' },
  { value: 'Polo', label: 'Polo' },
  { value: 'Handball', label: 'Handball' },
  { value: 'Other', label: 'Other' },
]
