export const SPORTS_LIST = [
  'Archery',
  'Badminton',
  'Baseball',
  'Basketball',
  'Bowling',
  'Boxing',
  'Cheerleading',
  'Cricket',
  'Cross Country',
  'Cycling',
  'Dance',
  'Diving',
  'Equestrian',
  'Esports',
  'Fencing',
  'Field Hockey',
  'Figure Skating',
  'Fishing',
  'Football',
  'Golf',
  'Gymnastics',
  'Handball',
  'Hockey',
  'Judo',
  'Karate',
  'Kayaking',
  'Lacrosse',
  'Marathon',
  'Martial Arts',
  'Mixed Martial Arts',
  'Motocross',
  'Mountain Biking',
  'Paintball',
  'Pickleball',
  'Polo',
  'Racquetball',
  'Rock Climbing',
  'Rowing',
  'Rugby',
  'Running',
  'Sailing',
  'Skateboarding',
  'Skiing',
  'Snowboarding',
  'Soccer',
  'Softball',
  'Squash',
  'Surfing',
  'Swimming',
  'Table Tennis',
  'Taekwondo',
  'Tennis',
  'Track and Field',
  'Triathlon',
  'Ultimate Frisbee',
  'Volleyball',
  'Water Polo',
  'Weightlifting',
  'Wrestling',
  'Yoga',
  'Other',
]
